### ISSUE TITLE
 Check access restrictions

### ISSUE THREAD

**Issue by CheckB** [nobodysu/zabbix-smartmontools#16]
zabbix_get -s 192.168.1.4 -k smartctl.discovery [get, "Example host"]
zabbix_get [26034]: Check access restrictions in Zabbix agent configuration

```
./smartctl-lld.py
Traceback (most recent call last):
   File "./smartctl-lld.py", line 354, in <module>
     host = '"% s"'% (sys.argv [2])
IndexError: list index out of range
```

```
#!/usr/bin/python3
```

```
 ./python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
```

Zabbix 4.0, debian 9
All the instructions

**Comment by nobodysu** [comment]
Local usage would be
`./smartctl-lld.py getverb "Example host"`

I guess the problem in Server or ServerActive directives. 
Do you have multiple NICs?

**Comment by CheckB** [comment]
> Do you have multiple NICs?

Yes

**Comment by nobodysu** [comment]
Then you must assign `SourceIP` in agent config to use appropriate net.

**Comment by nobodysu** [comment]
@CheckB 
Is it resolved?

**Comment by CheckB** [comment]
Yes, thx.
