### ISSUE TITLE
issue on installing

### ISSUE THREAD

**Issue by killmasta93** [nobodysu/zabbix-smartmontools#22]
**Describe the problem**
Hi,
I currently trying to install on proxmox debian 9 i followed the instruction but when i run the test currently getting this issue 
root@prometheus3:/etc# zabbix_get -s 192.168.3.160 -k smartctl.discovery[get,"prometheus3casa"]
zabbix_get [19259]: Check access restrictions in Zabbix agent configuration
- Zabbix server version: 4.4
Thank you

**Comment by nobodysu** [comment]
And the agent? Try 4.4.

**Comment by killmasta93** [comment]
i think its working after a few mins im seeing the data odd that the command wont work maybe im trying it wrong? 
![Screenshot from 2019-11-29 22-31-34](https://user-images.githubusercontent.com/13953629/69895124-0ac39280-12f8-11ea-8fde-0fa13effa7c6.png)

**Comment by nobodysu** [comment]
I don't understand. Please provide testing output:
```zabbix_get -s 192.0.2.1 -k smartctl.discovery[get,"Example host"]```
```zabbix_get -s 192.0.2.1 -k smartctl.discovery[getverb,"Example host"]```

**Comment by killmasta93** [comment]
when i run the command it gets stuck but for some reason its working
