### ISSUE TITLE
issue on installing 

### ISSUE THREAD

**Issue by killmasta93** [nobodysu/zabbix-smartmontools#23]
**Describe the problem**
Cannot seem to install on one particular server on debian 9

**To Reproduce**
apt-get install zabbix-agent smartmontools sudo

git clone https://github.com/nobodysu/zabbix-smartmontools.git

mkdir /etc/zabbix/scripts

cd zabbix-smartmontools/scripts/

mv smartctl-lld.py sender_wrapper.py /etc/zabbix/scripts/

cd /root/zabbix-smartmontools/Linux/

mv sudoers.d/zabbix /etc/sudoers.d/

cd /root/zabbix-smartmontools/Linux/zabbix_agentd.d/

mv userparameter_smartctl.conf /etc/zabbix/zabbix_agentd.conf.d/

cd /etc/zabbix/scripts

chmod 755 smartctl-lld.py sender_wrapper.py 

chown root:zabbix smartctl-lld.py sender_wrapper.py

cd /etc/zabbix/zabbix_agentd.conf.d/

chmod 644 userparameter_smartctl.conf

chown root:zabbix userparameter_smartctl.conf

cd /etc/

chmod 400 sudoers.d/zabbix

chown root sudoers.d/zabbix

restart zabbix`

**Expected behavior**

**Screenshots**

**Provide all outputs described in [Testing](https://github.com/nobodysu/zabbix-smartmontools#testing) step**
Serial numbers should be replaced with X_SERIAL_X.

**Please complete the following information:**
 - OS: debian 9 proxmox
 - Zabbix server version: 4.4
 - Active or passive check: active

**Additional context**
whats odd is that i have these same steps working on another server same version and everything

**Comment by nobodysu** [comment]
Please provide testing output:
`zabbix_get -s 192.0.2.1 -k smartctl.discovery[get,"Example host"]`
`zabbix_get -s 192.0.2.1 -k smartctl.discovery[getverb,"Example host"]`

**Comment by killmasta93** [comment]
Thanks for the reply, as for the zabbix_get command i could not install it, i tried 
root@prometheus2:~# apt-get install zabbix-get
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package zabbix-get

**Comment by nobodysu** [comment]
You can also do:
`/etc/zabbix/scripts/smartctl-lld.py getverb NON`

**Comment by killmasta93** [comment]
thanks for the quick reply i got this

https://pastebin.com/s3Jxr1ZD

**Comment by nobodysu** [comment]
Items from prototypes are created? If not, what discovery tells (Host -> Discovery rule -> SMART disk discovery)?

**Comment by killmasta93** [comment]
thanks for the reply, i see an error on info see picture
![Screenshot from 2019-12-08 16-53-55](https://user-images.githubusercontent.com/13953629/70396930-63bbb680-19db-11ea-978e-ad5ced2dae0f.png)

**Comment by nobodysu** [comment]
Well, that's expected and not a problem. I guess the items are created, but recheck please.
To answer further I need _full_ `geverb` output (including versions and settings). Also to troubleshoot you badly need `zabbix-get` on the server. Maybe `contrib` is not in sources.list? Maybe no agent package on the server?

**Comment by killmasta93** [comment]
Thanks for the reply, so what i did was remove the template and put it again now the error in red does not appear but i have been looking how to get the zabbix-get 
and as the full goverb im guessing i need the zabbix-get?

these are the apt sources 

deb http://download.proxmox.com/debian/pve stretch pve-no-subscription


deb http://ftp.debian.org/debian stretch main contrib

deb http://ftp.debian.org/debian stretch-updates main contrib

# security updates
deb http://security.debian.org stretch/updates main contrib

![Screenshot from 2019-12-08 19-55-22](https://user-images.githubusercontent.com/13953629/70399748-b6ee3300-19f4-11ea-84f4-2bb939972b5c.png)

Thank you

**Comment by killmasta93** [comment]
whats odd now is that now it shows but only shows Template configuration status
![Screenshot from 2019-12-08 21-17-32](https://user-images.githubusercontent.com/13953629/70402125-3e8d6f00-1a00-11ea-9b0e-a3c540bb253f.png)

**Comment by killmasta93** [comment]
after looking around i thought it was the timeout, i raised to 30 on server and agent but its odd how prometheus3 works and prometheus 2 and prometheus wont get 
![Screenshot from 2019-12-08 21-40-05](https://user-images.githubusercontent.com/13953629/70403023-6df1ab00-1a03-11ea-9d4a-599845fbb54b.png)

**Comment by killmasta93** [comment]
so after a while it started all 3 servers working and reporting after changing to all the agents to timeout 30 and server on zabbix ill post back in 24 hours to see if that worked
![Screenshot from 2019-12-08 22-15-14](https://user-images.githubusercontent.com/13953629/70404514-579a1e00-1a08-11ea-9fda-2d28cfccf446.png)
