### ISSUE TITLE
OSError: [Errno 7] Argument list too long: '/usr/local/bin/python3'

### ISSUE THREAD

**Issue by asomers** [nobodysu/zabbix-smartmontools#26]
**Describe the bug**
On a system with many disks (486 in my case) smartctl-lld.py will fail with the error `OSError: [Errno 7] Argument list too long: '/usr/local/bin/python3'`.  Could smartctl-lld.py split up the data and send it in multiple invocations?

**To Reproduce**
Simply run `/usr/local/etc/zabbix42/scripts/smartctl-lld.py getverb <hostname>` on a system with a lot of disks.

**Expected behavior**
Data should be sent to the zabbix master

**Screenshots**
```
# time /usr/local/etc/zabbix42/scripts/smartctl-lld.py getverb <hostname>
  Python version:
 3.7.5 (default, Dec  2 2019, 21:00:43) 
[Clang 8.0.1 (tags/RELEASE_801/final 366581)]

  Sender version:
 zabbix_sender (Zabbix) 4.2.8
Revision cb5d5b10f4 28 October 2019, compilation time: Dec  2 2019 22:10:18

Copyright (C) 2019 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1d-freebsd  10 Sep 2019
Running with OpenSSL 1.1.1d-freebsd  10 Sep 2019


  Config's main settings:
Server=efs-prd-zabbix3.mydomain,efs-dev-zabbix4.mydomain
ServerActive=efs-prd-zabbix3.mydomain,efs-dev-zabbix4.mydomain,10.2.172.22
Could not find 'Timeout' manual setting in config!
Default value is too low for this script.

/usr/local/etc/zabbix42/scripts/smartctl-lld.py: Could not send anything. Argument list or filepath too long. (HUGEDATA)
  Please report any issues or missing features to:
https://github.com/nobodysu/zabbix-smartmontools/issues

Traceback (most recent call last):
  File "/usr/local/etc/zabbix42/scripts/smartctl-lld.py", line 412, in <module>
    processData(senderData, jsonData, agentConf, senderPyPath, senderPath, timeout, host, link)
  File "/usr/local/etc/zabbix42/scripts/sender_wrapper.py", line 163, in processData
    subprocess.Popen(cmd, stdin=subprocess.PIPE, close_fds=(not isWindows()))
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/usr/local/bin/python3'
```

**Provide all outputs described in [Testing](https://github.com/nobodysu/zabbix-smartmontools#testing) step**
Serial numbers should be replaced with X_SERIAL_X.

**Please complete the following information:**
 - OS: FreeBSD 12.1-STABLE
 - Zabbix server version: 4.4.1
 - Active or passive check: Unsure
 - Using zabbix proxy: No

**Comment by nobodysu** [comment]
486, omg...
I've expected such scenario and planned a resolution - one smartctl call per disk. Do not have an ETA though.

**Comment by asomers** [comment]
I don't think a solution is that hard.  The crash doesn't happen when invoking `smartctl`; it happens when `sender_wrapper.py` reexecutes itself.  Why is that necessary anyway?  I could take a stab at fixing it.  But I have a few questions:
* How to you validate changes?  I don't see any CI.  Do you have to manually test on every platform?  I only have access to FreeBSD.
* I can't figure out how to make discovery work.  Even though I've set the discovery interval to 299 seconds and I've restricted the list of disks using `diskListManual`, my Zabbix server isn't picking up changes.  Do you have any advice?

**Comment by nobodysu** [comment]
I'm just testing it live. I can test your solution if you come up with something.

If it doesn't work with diskListManual - maybe multiple servers are a problem. I'm not aware how the script will behave it that scenario. getverb should be sufficient to debug almost anything.

The main problem is with the fact that data is transferred to sender_wrapper through parameter, and exceeds system-defined limit. Moreover, I think that 500 disk are unable to be queried within 30 seconds.
If you could come up with PIPE data transfer and configure cron to make the query - it can probably work. I break my mind implementing cross-platform PIPE, not sure if it's even possible.

And if you don't want the hassle - you can try out a different solution: https://github.com/v-zhuravlev/zbx-smartctl

**Comment by nobodysu** [comment]
I wonder, will [temperature monitoring](https://github.com/nobodysu/zabbix-mini-IPMI) work with 500 drives? With Timeout=30 ofc.

**Comment by asomers** [comment]
Ok, I fixed all of the discovery problems.  There are still two problems with large numbers of drives.
1) The argument list overflow
2) It takes too darn long

https://github.com/nobodysu/zabbix-smartmontools/pull/27 improves the testability of zabbix-smartmontools.  If you accept that, then I'll have the confidence to fix these problems.

**Comment by asomers** [comment]
I have a patch that prevents reexecution of sender_wrapper.py.  That will fix the "Argument list too long" error.  I'll post a PR after #27 is done.
