### ISSUE TITLE
no sender_wrapper.py?

### ISSUE THREAD

**Issue by killmasta93** [nobodysu/zabbix-smartmontools#31]
**Describe the problem**
Hi im trying to install smartmontools on another proxmox host but when i try 
```

cd zabbix-smartmontools/scripts/
mv smartctl-lld.py sender_wrapper.py /etc/zabbix/scripts/
```
these are the exact steps i take 

```
apt-get install zabbix-agent smartmontools sudo
git clone https://github.com/nobodysu/zabbix-smartmontools.git
mkdir /etc/zabbix/scripts
cd zabbix-smartmontools/scripts/
mv smartctl-lld.py sender_wrapper.py /etc/zabbix/scripts/
cd /root/zabbix-smartmontools/Linux/
mv sudoers.d/zabbix /etc/sudoers.d/
cd /root/zabbix-smartmontools/Linux/zabbix_agentd.d/
mv userparameter_smartctl.conf /etc/zabbix/zabbix_agentd.conf.d/
cd /etc/zabbix/scripts
chmod 755 smartctl-lld.py sender_wrapper.py
chown root:zabbix smartctl-lld.py sender_wrapper.py
cd /etc/zabbix/zabbix_agentd.conf.d/
chmod 644 userparameter_smartctl.conf
chown root:zabbix userparameter_smartctl.conf
cd /etc/
chmod 400 sudoers.d/zabbix
chown root sudoers.d/zabbix
restart zabbix
```

**Comment by nobodysu** [comment]
Take a look at the first README line - the installation process had changed.
Or use previous version.

**Comment by killmasta93** [comment]
Thanks for the reply, didnt not see it i tried using the new version when installing i got this error
```
root@prometheus:~/zabbix-smartmontools# sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
```
but i have python3
```
root@prometheus:~# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by killmasta93** [comment]
i had to install this 

`apt-get install python3-setuptools`

**Comment by killmasta93** [comment]
quick question on the data coming it does not show the values any ideas?
![image](https://user-images.githubusercontent.com/13953629/74253268-ddfb0680-4cbc-11ea-844e-4aaea74cea3a.png)
![image](https://user-images.githubusercontent.com/13953629/74253334-f10dd680-4cbc-11ea-9eca-70f6f409d934.png)

**Comment by asomers** [comment]
@killmasta93 the easiest thing for you would be to run a released version, not git master.

**Comment by killmasta93** [comment]
thanks for the reply, but the released version 1.5.5  there is no setup.py it seems like it was the old version?

**Comment by asomers** [comment]
That's right.  The latest release used a different installation procedure.  Read the README in that release for more information.

**Comment by killmasta93** [comment]
hmmm alright what i havent not done yet is update the template.xml

**Comment by nobodysu** [comment]
@killmasta93 These errors are cosmetic and will not interfere with the process.

**Comment by killmasta93** [comment]
very odd once i put in the old version it started to show the data, ill postback on another proxmox box that im going to update

**Comment by asomers** [comment]
@killmasta93 the master branch is a WIP.  You really shouldn't use it unless you're developing zabbix-smartmontools.  You should still to released versions instead.

**Comment by killmasta93** [comment]
thanks will keep that in mind
