### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Vardancer** [nobodysu/zabbix-smartmontools#8]
Hi I'm getting errors about duplicate items can't be added
![screenshot_2018-07-20_08-39-56](https://user-images.githubusercontent.com/34734915/42995604-f42e5da4-8c19-11e8-9274-ab8cf62ca3ac.png)
Can you help me?
I added custom disk list, like '/dev/sda -d sat+megaraid,4' and so on.
Zabbix version 3.4

**Comment by nobodysu** [comment]
Yeah, thats common cosmetic error. Did you check items creation on the host? It should be there. Data will arrive after next run (on Windows).
Post [Testing](https://github.com/nobodysu/zabbix-smartmontools#testing) output please.

**Comment by nobodysu** [comment]
Related https://github.com/nobodysu/zabbix-smartmontools/issues/7

**Comment by Vardancer** [comment]
[smartctl_lld_linux.txt](https://github.com/nobodysu/zabbix-smartmontools/files/2218058/smartctl_lld_linux.txt)
[smartctl_lld_windows.txt](https://github.com/nobodysu/zabbix-smartmontools/files/2218059/smartctl_lld_windows.txt)

Here is testing output.
I did read that data will arrive from win on next run, but those errors from linux machine, and I dont understand how to fix it.
Thanks

**Comment by nobodysu** [comment]
Please also provide getverb output from hosts:
`zabbix_get -s 192.0.2.1 -k smartctl.discovery[getverb,"Example host"]`

You should investigate web interface:
`Example host - Items - Template App smartmontools: SMART values - Items`

**Comment by Vardancer** [comment]
[smartctl_lld_windows_verb.txt](https://github.com/nobodysu/zabbix-smartmontools/files/2219525/smartctl_lld_windows_verb.txt)
couldn't get 'getverb' from linux machine because of timeout even with Timeout=20

**Comment by nobodysu** [comment]
> couldn't get 'getverb' from linux machine
That's the root of the problem, not these cosmetic errors! 
Make it 30 seconds, restart agent. If that does not help - run script locally:
`./smartctl-lld.py getverb "Example host"`

How much disks does linux machine have btw?

**Comment by nobodysu** [comment]
It's better to use
`time ./smartctl-lld.py getverb "Example host"`

**Comment by Vardancer** [comment]
Well items are created on linux
I ran `./smartctl-lld.py getverb "my hostname"` and after normal output I've got 

> zabbix_sender [24455]: Warning: timeout while executing operation
sent: 79; skipped: 0; total: 79
machine have 4 disks, but I enabled in config 2 those in first raid

**Comment by nobodysu** [comment]
That's firewall or selinux blocking port 10051 on server side. (or outbound on client side)

**Comment by Vardancer** [comment]
yeah, the problem was I needed to setup source ip in zabbix client conf.
Big thank you for help. Now all fine.
