### ISSUE TITLE
No New Info

### ISSUE THREAD

**Issue by reginfo** [nobodysu/zabbix-smartmontools#9]
Hi, 

I trying to use your script. 
Everything seems works when I executing script by hand.
But no data refresh occurs. 

Can you please help me?

**Comment by nobodysu** [comment]
Have you waited for 12 hours (24 for windows)?
Please provide [testing](https://github.com/nobodysu/zabbix-smartmontools#testing) outputs.

**Comment by nobodysu** [comment]
Hope that was resolved.
